import type { Metadata } from "next";
import MainNav from "@/components/MainNav";

import "./globals.css";

export const metadata: Metadata = {
  title: "Crypto Checker",
  description: "Generated by NivekTzu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
